apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app-deployment
spec:
  replicas: 1   selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: angular-app-container
          image: majidmashhadi/angular-app:1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app-service
spec:
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: angular-app-ingress
spec:
  rules:
    - host: localhost # Replace with your actual domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: angular-app-service
                port:
                  number: 80
#kubectl port-forward service/angular-app-service 8080:80
#kubectl port-forward service/angular-app-service 8080:80
